version: 2
jobs:
  build:
    working_directory: ~/stencil
    docker:
      - image: circleci/node:6
    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run: npm install --no-save
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: npm install npm@latest
      - run: npm run build
      - run: npm run test.jest -- --maxWorkers=4
